name: Get Sleep Data
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  get-sleep-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies  
      run: npm install
    - name: Start program
      run: node app.js /start
